### ISSUE TITLE
在编译时报找不到方法的错误

### ISSUE THREAD

**Issue by PikachuHy** [linuxdeepin/deepin-voice-recorder#3]
```
app.setProductIcon(QPixmap::fromImage(QImage(Utils::getQrcPath("logo_96.png"))));
app.setProductName(DApplication::translate("MainWindow", "Deepin Voice Recorder"));
app.setApplicationDescription(DApplication::translate("MainWindow", descriptionText) + "\n");
app.setApplicationAcknowledgementPage(acknowledgementLink);
```
报错是
../deepin-voice-recorder/src/main.cpp: In function ‘int main(int, char**)’:
../deepin-voice-recorder/src/main.cpp:56:13: error: ‘class Dtk::Widget::DApplication’ has no member named ‘setProductIcon’; did you mean ‘setWindowIcon’?
         app.setProductIcon(QPixmap::fromImage(QImage(Utils::getQrcPath("logo_96.png"))));
             ^~~~~~~~~~~~~~
../deepin-voice-recorder/src/main.cpp:57:13: error: ‘class Dtk::Widget::DApplication’ has no member named ‘setProductName’; did you mean ‘setObjectName’?
         app.setProductName(DApplication::translate("MainWindow", "Deepin Voice Recorder"));
             ^~~~~~~~~~~~~~
../deepin-voice-recorder/src/main.cpp:58:13: error: ‘class Dtk::Widget::DApplication’ has no member named ‘setApplicationDescription’; did you mean ‘setApplicationVersion’?
         app.setApplicationDescription(DApplication::translate("MainWindow", descriptionText) + "\n");
             ^~~~~~~~~~~~~~~~~~~~~~~~~
../deepin-voice-recorder/src/main.cpp:59:13: error: ‘class Dtk::Widget::DApplication’ has no member named ‘setApplicationAcknowledgementPage’; did you mean ‘setApplicationDisplayName’?
         app.setApplicationAcknowledgementPage(acknowledgementLink);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by manateelazycat** [comment]
It's git version dtk, you need compile git version deepin-tool-kit first
