### ISSUE TITLE
executable svg

### ISSUE THREAD

**Issue by yangfl** [linuxdeepin/deepin-voice-recorder#4]
./manual/en_US/icon/Enter.svg
./manual/en_US/icon/close_icon.svg
./manual/zh_CN/icon/Enter.svg
./manual/zh_CN/icon/close_icon.svg
./manual/zh_CN/icon/tips.svg

**Comment by manateelazycat** [comment]
has fxied by patch : https://github.com/linuxdeepin/deepin-voice-recorder/commit/8110e412329f69b3b4a03a6458f70e56789dfadc

thanks!
